### ISSUE TITLE
Create Health Plan Blocks block category inside the LSX Blocks that will only display with the LSX HP plugin active

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-blocks#23]
**Description**
Create Health Plan Blocks block category inside the LSX Blocks that will only display with the LSX HP plugin active, this section will have all the plugins related to the LSX Health Plan plugin.

**To do**
- [x] Require the LSX Health Plan Plugin first, so all the blocks related to HP Plan will show.
- [x] Create a new block section just for HP blocks.

**New Block sections should look like this**
<img width="442" alt="Screen Shot 2020-02-07 at 10 23 33 PM" src="https://user-images.githubusercontent.com/3129483/74076690-96445880-49f8-11ea-825f-b0ca269b8460.png">

**Call the following blocks inside this category:**
- [ ] Featured Workouts videos block -> https://github.com/lightspeeddevelopment/lsx-blocks/issues/29
- [ ] FAQs block (this is a new post type coming)
- [ ] Featured Tips block -> https://github.com/lightspeeddevelopment/lsx-blocks/issues/30
- [ ] Featured recipes block -> https://github.com/lightspeeddevelopment/lsx-blocks/issues/31
- [ ] Weekly plan grid view block -> https://github.com/lightspeeddevelopment/lsx-blocks/issues/32
- [ ] Daily plan grid view block - > https://github.com/lightspeeddevelopment/lsx-blocks/issues/33

**Comment by viscosho** [comment]
@krugazul  this commit on the HP branch is to make the HP block category and make sure that those blocks only load if the health plan plugin is enabled: https://github.com/lightspeeddevelopment/lsx-blocks/commit/ae395af0146552d0e0c09d20c91f9a5902805aef
